// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurnosMedicos.Api.Data;

#nullable disable

namespace TurnosMedicos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228204150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TurnosMedicos.Api.Domain.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadTratamientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadTratamientoId");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cel")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadTratamientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadTratamientoId");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.MedicoEspecialidad", b =>
                {
                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.HasKey("MedicoId", "EspecialidadId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("MedicosEspecialidades");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.ObraSocial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ObrasSociales");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cel")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("ObraSocialId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("ObraSocialId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.UnidadTratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnidadesTratamiento");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.Especialidad", b =>
                {
                    b.HasOne("TurnosMedicos.Api.Domain.UnidadTratamiento", "UnidadTratamiento")
                        .WithMany("Especialidades")
                        .HasForeignKey("UnidadTratamientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadTratamiento");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.Medico", b =>
                {
                    b.HasOne("TurnosMedicos.Api.Domain.UnidadTratamiento", "UnidadTratamiento")
                        .WithMany("Medicos")
                        .HasForeignKey("UnidadTratamientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UnidadTratamiento");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.MedicoEspecialidad", b =>
                {
                    b.HasOne("TurnosMedicos.Api.Domain.Especialidad", "Especialidad")
                        .WithMany("MedicosEspecialidades")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnosMedicos.Api.Domain.Medico", "Medico")
                        .WithMany("MedicosEspecialidades")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.Turno", b =>
                {
                    b.HasOne("TurnosMedicos.Api.Domain.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnosMedicos.Api.Domain.Medico", "Medico")
                        .WithMany("Turnos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnosMedicos.Api.Domain.ObraSocial", "ObraSocial")
                        .WithMany("Turnos")
                        .HasForeignKey("ObraSocialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnosMedicos.Api.Domain.Paciente", "Paciente")
                        .WithMany("Turnos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");

                    b.Navigation("ObraSocial");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.Especialidad", b =>
                {
                    b.Navigation("MedicosEspecialidades");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.Medico", b =>
                {
                    b.Navigation("MedicosEspecialidades");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.ObraSocial", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.Paciente", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("TurnosMedicos.Api.Domain.UnidadTratamiento", b =>
                {
                    b.Navigation("Especialidades");

                    b.Navigation("Medicos");
                });
#pragma warning restore 612, 618
        }
    }
}
